'use strict';

module.exports = {
  en: {
    name: 'English',
    brevity: ['in short', 'in brief', 'briefly', 'tldr', 'be brief', 'be concise', 'be short', 'keep it short', 'keep it brief', 'keep it concise', 'keep it tight', 'keep it simple', 'short answer*', 'short version', 'shorter please', 'get to the point', 'straight to the point', 'to the point', 'no fluff', 'less text', 'fewer words', 'stop rambling', 'no essay*', 'not an essay', 'one line', 'one liner', 'one sentence', 'in a sentence', 'in a few words', 'in two sentences', 'in 2 sentences', 'in a few lines', 'just the answer', 'just the command', 'just give me the', 'concise*', 'succinct*', 'wall of text', 'too much text', 'too much to read', 'tl dr', 'shorter answers', 'shorter replies', 'shorter responses', 'less talk more code', 'less talking more code', 'not gonna read', 'not going to read', 'wont read all', 'won\'t read all', 'not reading all', 'yes or no', 'yes/no', 'quick yes', 'cut it in half', 'shorten it', 'make it shorter', 'in a nutshell', 'tldr please', 'long story short', 'spare me the', 'skip the essay', 'dont explain', 'don\'t explain'],
    long: ['long', 'longer', 'lengthy', 'verbose', 'wordy', 'rambl*', 'long-winded', 'long winded'],
    too: ['too', 'way too', 'overly', 'so damn', 'super'],
    short: ['short', 'shorter', 'brief', 'briefer', 'concise', 'compact', 'terse'],
    reply: ['answer*', 'reply', 'replies', 'respons*', 'message*', 'explanation*', 'explain*', 'write', 'writing', 'text'],
    code: ['function*', 'method*', 'variable*', 'name', 'names', 'code', 'file*', 'class', 'classes', 'url*', 'link*', 'string*', 'list', 'lists', 'array*', 'log', 'logs', 'logfile*', 'table*', 'column*', 'title*', 'label*', 'query*', 'path*', 'commit*', 'branch*', 'script*', 'timeout*', 'password*', 'key*', 'loop*', 'component*', 'module*', 'snippet*', 'regex*', 'url', 'slug*', 'id', 'ids', 'video*', 'image*', 'data', 'dataset*', 'csv', 'json', 'pr', 'diff', 'diffs', 'route*', 'endpoint*', 'parameter*', 'param*', 'argument*', 'description*', 'readme*', 'doc', 'docs', 'document*', 'summary', 'summaries', 'summarize*', 'summarise*', 'section*', 'prs', 'pull request*', 'changelog*', 'comment*', 'commit message*', 'email*', 'api', 'apis', 'payload*', 'field*', 'character*', 'chars', 'paginat*', 'response body', 'tweet*', 'post', 'blog*', 'article*', 'headline*', 'tooltip*', 'error message*', 'release note*'],
    detail: ['detail*', 'in depth', 'in-depth', 'thorough*', 'elaborat*', 'comprehensive*', 'walk me through', 'deep dive', 'explain everything', 'full explanation', 'long version', 'step by step', 'longer explanation', 'go deep', 'deep-dive', 'all the details', 'at length', 'exhaustive*', 'in great detail', 'thoroughly', 'granular'],
    permission: ['can', 'may', 'fine', 'ok', 'okay', 'feel free', 'allowed', 'go ahead', 's ok", ', 'are fine', 'is fine', 'is ok', 'are ok'],
    lift: ['no need to be brief', 'no need to be short', 'no need to keep it short', 'stop being brief', 'dont have to be brief', 'dont need to be brief', 'dont need to keep it short', 'dont have to keep it short', 'longer answers are fine', 'longer replies are fine', 'as much as you want', 'as long as you want', 'go long', 'take your time explaining'],
    standing: ['always', 'never', 'from now on', 'going forward', 'every time', 'each time', 'anymore', 'any more', 'from here on', 'in every', 'in all your', 'every answer', 'every reply', 'every response', 'dont ever', 'don\'t ever', 'do not ever', 'ever again', 'whenever you', 'every single time'],
    oneOff: ['for now', 'this time', 'right now', 'just this once', 'for this one', 'just now'],
    negation: ['no', 'dont', 'do not', 'without', 'stop', 'avoid', 'never', 'drop the', 'lose the'],
    emoji: ['emoji*', 'emoticon*', 'smiley*'],
    stop: ['the', 'and', 'is', 'you', 'to', 'it', 'of', 'what', 'this', 'that', 'please', 'with', 'for', 'not', 'are', 'can', 'how', 'why', 'just', 'my', 'me', 'your', 'dont', 'be', 'a', 'i', 'in', 'on', 'do', 'does', 'so', 'we', 'its', 'it\'s', 'im', 'pls', 'plz', 'ok', 'okay', 'yes', 'no', 'or', 'here', 'there', 'have', 'has', 'will', 'was'],
    much: ['much', 'many words', 'a lot'],
    skip: ['skip', 'stop', 'no need', 'dont need', 'don\'t need', 'spare me', 'cut the', 'drop the', 'without the', 'enough'],
    explain: ['explanation*', 'explaining', 'over-explaining', 'overexplaining', 'over explaining', 'lecture*', 'talk', 'talking', 'chatter', 'blabla', 'yapping', 'fluff', 'theory', 'details'],
    longform: ['essay*', 'novel*', 'thesis', 'dissertation*', 'bible', 'book', 'books', 'epic', 'saga', 'wall', 'walls', 'paragraphs', 'lecture', 'manifesto'],
    text: ['text', 'words', 'wall of', 'paragraphs', 'reading'],
    cancel: ['forget', 'scratch', 'nvm', 'never mind', 'ignore', 'drop', 'cancel', 'undo', 'disregard', 'lift', 'scrap', 'retract', 'lift the'],
    noNeed: ['no need', 'dont have to', 'don\'t have to', 'dont need', 'don\'t need', 'no longer need', 'not necessary', 'not needed'],
    again: ['again', 'back to', 'anymore', 'any more', 'now', 'from now on', 'from here on', 'going forward'],
    briefNoun: ['brevity', 'brief', 'concise', 'short answers', 'short', 'the rule', 'terse', 'brevity thing'],
    answer: ['answer*', 'reply', 'replies', 'your response*', 'your message*', 'your explanation*', 'you write', 'you re writing', 'your text'],
    strong: ['less talk more code', 'less talking more code', 'yes or no', 'yes/no', 'quick yes', 'not gonna read', 'not going to read', 'wont read all', 'not reading all', 'in one line', 'in one sentence', 'one sentence answer', 'tldr', 'straight to the point', 'get to the point', 'to the point'],
  },
  tr: {
    name: 'Turkish',
    brevity: ['kisaca', 'kisacasi', 'kisa ve oz', 'kisa ve net', 'kisa kes', 'kisa tut', 'kisa yaz', 'lafi uzatma', 'uzatma', 'ozet gec', 'tek cumle*', 'bir cumle*', 'birkac cumle*', 'birkac kelime*', 'net soyle', 'direkt soyle', 'roman yazma', 'destan yazma', 'makale yazma', 'uzun yazma', 'uzun uzun yazma', 'uzun yaziyorsun', 'cok yaziyorsun', 'cok uzun', 'sadece cevab*', 'sadece cevap', 'kisa olsun', 'kisa cevap*', 'kisa yanit*', 'ozetle soyle', 'tek satir*', 'kisaltir misin cevab*', 'az laf cok kod', 'az laf', 'laf dolandirma', 'lafi dolandirma', 'okumam', 'okumayacagim', 'evet hayir', 'evet mi hayir mi', 'kisalt', 'kisalt sunu', 'kisaltir misin', 'ozet olarak', 'kisaca soyle', 'fazla detay verme', 'detaya girme', 'roman yazmis*', 'destan yazmis*'],
    long: ['uzun*', 'uzat*'],
    too: ['cok', 'fazla', 'asiri', 'gereginden fazla', 'acayip'],
    short: ['kisa*', 'oz', 'net'],
    reply: ['cevap*', 'cevab*', 'yanit*', 'mesaj*', 'aciklama*', 'yaz*', 'anlat*', 'soyle*'],
    code: ['fonksiyon*', 'metod*', 'method*', 'degisken*', 'isim*', 'ismi', 'adi', 'kod', 'kodu', 'kodun', 'kodlar*', 'dosya*', 'satir', 'satiri', 'satirlar*', 'sinif*', 'url*', 'link*', 'liste*', 'dizi*', 'log', 'loglar*', 'logu', 'tablo*', 'kolon*', 'sutun*', 'baslik*', 'sorgu*', 'commit*', 'script*', 'bilesen*', 'component*', 'sifre*', 'video*', 'resim*', 'gorsel*', 'veri*', 'aciklamasi', 'readme*', 'dokuman*', 'ozetle', 'ozetini', 'ozet cikar*', 'bolum*', 'alan*', 'karakter*', 'yorum*', 'makale*', 'test', 'testi', 'testler*', 'testleri'],
    detail: ['detay*', 'ayrinti*', 'derinlemesine', 'tum detay*', 'butun detay*', 'her seyi anlat', 'adim adim', 'aciklamali', 'enine boyuna', 'uzun uzun anlat', 'genis genis', 'detayli', 'detayca', 'ayrintili'],
    permission: ['yazabilirsin', 'anlatabilirsin', 'olabilir', 'sorun degil', 'sorun yok', 'serbest', 'olur', 'olabilirsin', '*ebilirsin', '*abilirsin', '*ebilirsiniz', '*abilirsiniz'],
    lift: ['kisa yazmana gerek yok', 'kisa tutmana gerek yok', 'kisa yazmak zorunda degilsin', 'artik uzun yaz*', 'artik detayli yaz*', 'uzun yazabilirsin', 'detayli yazabilirsin', 'uzun olabilir'],
    standing: ['her zaman', 'hep', 'asla', 'hicbir zaman', 'hic bir zaman', 'bundan sonra', 'her seferinde', 'her cevap*', 'her cevab*', 'her yanit*', 'her mesaj*', 'daima', 'artik hic', 'her dosya*', 'her degisiklik*', 'her commit*', 'her push*', 'surekli', 'devamli'],
    oneOff: ['simdilik', 'simdi', 'bu sefer', 'bu seferlik', 'bu kez', 'bir kereligine', 'su an icin'],
    negation: ['kullanma', 'olmasin', 'olmadan', 'yok', 'koyma', 'ekleme', 'istemiyorum'],
    emoji: ['emoji*'],
    stop: ['ve', 'bir', 'bu', 'icin', 'ne', 'mi', 'degil', 'bana', 'su', 'ile', 'da', 'de', 'cok', 'neden', 'nasil', 'ama', 'gibi', 'olsun', 'yap', 'misin', 'lutfen', 'sadece', 'hala', 'neler', 'abi', 'sonra', 'daha', 'kadar', 'her', 'ya', 'yaa', 'olarak', 'simdi', 'once', 'bunu', 'sunu', 'onu', 'direkt', 'tamam', 'evet', 'hayir', 'beni', 'sen', 'ben', 'hep', 'bundan', 'cevap', 'ver', 'yaz', 'anlat', 'nedir', 'yok', 'var', 'oldu', 'olmadi', 'diye', 'ki'],
    chars: /[ığş]/,
    much: ['fazla', 'cok', 'kadar'],
    skip: ['gec', 'gecelim', 'atla', 'gerek yok', 'birak', 'kes', 'yeter'],
    explain: ['aciklama*', 'anlatma', 'teori', 'laf', 'detay'],
    longform: ['roman', 'destan', 'makale', 'kitap', 'tez', 'ansiklopedi', 'sayfa sayfa', 'paragraf paragraf'],
    text: ['yazi', 'yaziyi', 'metin', 'kelime', 'laf', 'satir satir'],
    cancel: ['unut', 'bosver', 'iptal', 'vazgec', 'kaldir', 'sil', 'unut onu', 'iptal et*'],
    noNeed: ['gerek yok', 'zorunda degilsin', 'sart degil', 'lazim degil'],
    again: ['artik', 'yine', 'tekrar', 'eskisi gibi', 'bundan sonra', 'donebilirsin'],
    briefNoun: ['kisa', 'kisalik', 'kisa tut', 'kisa yaz', 'kural'],
    answer: ['cevap*', 'cevab*', 'yanit*'],
    strong: ['az laf cok kod', 'roman yazmis*', 'destan yazmis*', 'az laf', 'lafi dolandirma', 'laf dolandirma', 'lafi uzatma', 'evet hayir', 'evet mi hayir mi', 'tek cumleyle', 'tek satirda', 'okumam', 'okumayacagim'],
  },
  es: {
    name: 'Spanish',
    brevity: ['en resumen', 'en pocas palabras', 'brevemente', 'se breve', 'se conciso', 'se concisa', 'mas corto', 'mas corta', 'respuestas cortas', 'respuesta corta', 'respuestas breves', 'respuesta breve', 'al grano', 've al grano', 'sin rodeos', 'en una linea', 'en una frase', 'en dos frases', 'menos texto', 'no tan largo', 'solo la respuesta', 'resumido', 'resumelo', 'corto porfa', 'corto por favor', 'sin tanto texto', 'no me escribas un libro', 'demasiado texto', 'mas breve', 'abrevia', 'en corto', 'menos charla mas codigo', 'no voy a leer', 'no lo voy a leer', 'si o no', 'acortalo', 'acorta', 'hazlo mas corto', 'en resumidas cuentas', 'sin explicacion', 'sin explicaciones', 'deja de explicar', 'sin tanto rollo'],
    long: ['largo*', 'larga*', 'extens*', 'verbos*', 'rollo'],
    too: ['demasiado*', 'muy', 'tan', 'super'],
    short: ['corto*', 'corta*', 'breve*', 'concis*', 'resumid*', 'escueto*', 'escueta*'],
    reply: ['respuesta*', 'responde*', 'contesta*', 'mensaje*', 'explica*', 'escrib*', 'texto*'],
    code: ['funcion*', 'metodo*', 'variable*', 'nombre*', 'codigo', 'archivo*', 'clase*', 'url*', 'enlace*', 'cadena*', 'lista*', 'array*', 'log', 'logs', 'tabla*', 'columna*', 'titulo*', 'prueba*', 'consulta*', 'commit*', 'script*', 'componente*', 'contrasena*', 'video*', 'imagen*', 'datos', 'resume este', 'resume el', 'resumen del', 'resumen de', 'seccion*', 'descripcion*', 'campo*', 'caracteres', 'comentario*', 'articulo*', 'test', 'tests'],
    detail: ['detalle*', 'detallad*', 'a fondo', 'en profundidad', 'exhaustiv*', 'paso a paso', 'explica todo', 'explicame todo', 'con todo detalle', 'extiendete', 'explayate', 'detall*', 'minucios*', 'pormenoriz*', 'a profundidad', 'extender*', 'extiend*'],
    permission: ['puedes', 'podes', 'esta bien', 'vale', 'ok', 'no pasa nada', 'estan bien'],
    lift: ['no hace falta ser breve', 'no tienes que ser breve', 'ya no tienes que ser breve', 'ya puedes extenderte', 'puedes extenderte', 'no hace falta que seas breve', 'puedes ser mas detallado', 'lo que quieras', 'todo lo que quieras'],
    standing: ['siempre', 'nunca', 'jamas', 'a partir de ahora', 'de ahora en adelante', 'cada vez', 'en adelante', 'en todas tus', 'en cada respuesta'],
    oneOff: ['por ahora', 'esta vez', 'de momento', 'por el momento', 'solo esta vez'],
    negation: ['sin', 'no uses', 'no pongas', 'nada de', 'no metas'],
    emoji: ['emoji*', 'emoticono*'],
    stop: ['el', 'la', 'de', 'que', 'y', 'en', 'los', 'las', 'por', 'con', 'para', 'una', 'es', 'no', 'como', 'esto', 'porfa', 'tu', 'tus', 'mas', 'muy', 'pero', 'esta', 'hazlo', 'dame', 'puedes', 'me', 'mi', 'lo', 'le', 'se', 'al', 'del', 'si', 'ya', 'porque', 'cual', 'donde', 'todo', 'eso', 'solo', 'asi', 'sin', 'hay', 'estan', 'puedo', 'quiero', 'dime', 'haz', 'hace', 'tambien', 'vale', 'oye', 'pues', 'sí'],
    chars: /[ñ¿¡]/,
    much: ['mucho', 'tanto', 'demasiado'],
    skip: ['saltate', 'salta', 'sin', 'deja de', 'basta de', 'no hace falta', 'olvidate de'],
    explain: ['explicacion*', 'explicar', 'explicando', 'rollo', 'charla', 'teoria', 'sermon'],
    longform: ['biblia', 'libro', 'novela', 'ensayo', 'tesis', 'testamento', 'parrafos', 'sermon'],
    text: ['texto', 'palabras', 'parrafos'],
    cancel: ['olvida', 'cancelo', 'cancela*', 'olvidate', 'ignora', 'cancela', 'quita'],
    noNeed: ['no hace falta', 'no tienes que', 'ya no', 'no es necesario', 'no necesitas'],
    again: ['otra vez', 'de nuevo', 'volver', 'vuelve', 'ya', 'ahora', 'a partir de ahora'],
    briefNoun: ['breve', 'brevedad', 'corto', 'corta', 'conciso', 'concisa', 'regla'],
    answer: ['respuesta*'],
    strong: ['menos texto mas codigo', 'menos charla mas codigo', 'menos rollo mas codigo', 'si o no', 'no voy a leer', 'en una linea', 'en una frase', 'al grano'],
  },
  pt: {
    name: 'Portuguese',
    brevity: ['resumindo', 'em resumo', 'em poucas palavras', 'seja breve', 'seja conciso', 'seja concisa', 'seja direto', 'seja direta', 'vai direto ao ponto', 'direto ao ponto', 'mais curto', 'mais curta', 'resposta curta', 'respostas curtas', 'resposta breve', 'respostas breves', 'em uma linha', 'numa linha', 'em uma frase', 'numa frase', 'menos texto', 'sem enrolacao', 'so a resposta', 'brevemente', 'textao', 'nao escreve um livro', 'mais objetivo', 'mais objetiva', 'seja objetivo', 'seja objetiva', 'resume ai', 'menos papo mais codigo', 'nao vou ler', 'nao vou ler isso', 'sim ou nao', 'encurta', 'resume isso', 'sem explicacao', 'para de explicar', 'pula a explicacao', 'sem textao', 'explica rapidinho', 'rapidinho'],
    long: ['longo*', 'longa*', 'extens*', 'prolix*', 'grande demais'],
    too: ['demais', 'muito', 'tao', 'super'],
    short: ['curto*', 'curta*', 'breve*', 'concis*', 'resumid*', 'objetiv*', 'rapidinho', 'rapido'],
    reply: ['resposta*', 'responde*', 'mensage*', 'explica*', 'escrev*', 'texto*'],
    code: ['funcao*', 'funcoes', 'metodo*', 'variave*', 'nome*', 'codigo', 'arquivo*', 'ficheiro*', 'classe*', 'url*', 'link*', 'string*', 'lista*', 'array*', 'log', 'logs', 'tabela*', 'coluna*', 'titulo*', 'teste*', 'consulta*', 'commit*', 'script*', 'componente*', 'senha*', 'video*', 'imagem*', 'dados', 'resume esse', 'resume este', 'resumo do', 'resumo da', 'secao', 'descricao*', 'campo*', 'caracteres', 'comentario*', 'artigo*', 'test', 'tests'],
    detail: ['detalhad*', 'detalhe*', 'a fundo', 'em profundidade', 'aprofundad*', 'passo a passo', 'explica tudo', 'explique tudo', 'com detalhes', 'pode se estender', 'detalh*', 'minucios*', 'pormenoriz*'],
    permission: ['pode', 'podes', 'tudo bem', 'ok', 'ta bom', 'tranquilo', 'estao bem'],
    lift: ['nao precisa ser breve', 'nao precisa resumir', 'pode se estender', 'nao precisa mais ser breve', 'pode escrever mais', 'pode ser mais detalhado', 'o quanto quiser', 'quanto quiser'],
    standing: ['sempre', 'nunca', 'jamais', 'a partir de agora', 'daqui pra frente', 'daqui para frente', 'toda vez', 'de agora em diante', 'em todas as respostas'],
    oneOff: ['por enquanto', 'desta vez', 'dessa vez', 'por agora', 'so dessa vez', 'so desta vez'],
    negation: ['sem', 'nao use', 'nao coloque', 'nada de', 'nao bota'],
    emoji: ['emoji*'],
    stop: ['o', 'a', 'de', 'que', 'e', 'do', 'da', 'em', 'um', 'uma', 'para', 'com', 'nao', 'voce', 'isso', 'pra', 'esse', 'essa', 'mais', 'muito', 'ta', 'me', 'faz', 'pode', 'tudo', 'so', 'eu', 'tu', 'ele', 'meu', 'minha', 'no', 'na', 'nos', 'nas', 'os', 'as', 'por', 'mas', 'se', 'ja', 'tem', 'to', 'aqui', 'ai', 'qual', 'quando', 'porque', 'pq', 'cara', 'mano', 'kkkk', 'vou', 'quero', 'preciso', 'posso'],
    chars: /[ãõ]/,
    much: ['muito', 'tanto', 'demais'],
    skip: ['pula', 'sem', 'para de', 'chega de', 'nao precisa', 'esquece'],
    explain: ['explicacao*', 'explicar', 'explicando', 'papo', 'enrolacao', 'teoria', 'sermao'],
    longform: ['redacao', 'biblia', 'livro', 'textao', 'tese', 'monografia', 'testamento', 'paragrafos'],
    text: ['texto', 'palavras', 'paragrafos'],
    cancel: ['esquece', 'ignora', 'cancela', 'tira'],
    noNeed: ['nao precisa', 'nao tem que', 'nao e necessario', 'nao precisa mais'],
    again: ['de novo', 'voltar', 'pode voltar', 'agora', 'daqui pra frente', 'outra vez'],
    briefNoun: ['breve', 'curto', 'curta', 'conciso', 'concisa', 'resumido', 'regra'],
    answer: ['resposta*'],
    strong: ['menos texto mais codigo', 'menos papo mais codigo', 'sim ou nao', 'nao vou ler', 'numa linha', 'em uma linha', 'numa frase', 'direto ao ponto'],
  },
  fr: {
    name: 'French',
    brevity: ['en bref', 'en resume', 'bref', 'brievement', 'sois bref', 'sois breve', 'sois concis', 'sois concise', 'soyez bref', 'soyez concis', 'plus court', 'plus courte*', 'reponse courte', 'reponses courtes', 'va a l essentiel', 'va droit au but', 'droit au but', 'a l essentiel', 'en une ligne', 'en une phrase', 'en deux phrases', 'moins de texte', 'pas de pave', 'pas de roman', 'juste la reponse', 'fais court', 'fais plus court', 'resume en', 'moins de blabla', 'pas de blabla', 'vais pas lire', 'je lirai pas', 'oui ou non', 'raccourcis', 'abrege', 'abrège', 'sans explication', 'arrete d expliquer', 'zappe l explication', 'vite fait'],
    long: ['long*', 'longue*', 'verbeu*', 'pave*'],
    too: ['trop', 'beaucoup trop', 'tres', 'vraiment'],
    short: ['court*', 'courte*', 'bref', 'breve*', 'concis*', 'succinct*', 'rapidement', 'vite'],
    reply: ['reponse*', 'repond*', 'message*', 'explication*', 'explique*', 'ecri*', 'texte*'],
    code: ['fonction*', 'methode*', 'variable*', 'nom', 'noms', 'code', 'fichier*', 'classe*', 'url*', 'lien*', 'chaine*', 'liste*', 'tableau*', 'log', 'logs', 'colonne*', 'titre*', 'requete*', 'commit*', 'script*', 'composant*', 'mot de passe', 'video*', 'image*', 'donnees', 'resume ce', 'resume le', 'resume du', 'section*', 'description*', 'champ*', 'caracteres', 'commentaire*', 'article*', 'test', 'tests'],
    detail: ['detail*', 'en profondeur', 'approfondi*', 'exhausti*', 'pas a pas', 'etape par etape', 'explique tout', 'tout expliquer', 'developpe', 'minutieu*', 'a fond', 'en detail', 'developp*'],
    permission: ['peux', 'pouvez', 'c est bon', 'ca va', 'ok', 'd accord', 'libre'],
    lift: ['pas besoin d etre bref', 'plus besoin d etre bref', 'tu peux developper', 'pas besoin de faire court', 'tu n as plus besoin d etre bref', 'tu peux etre plus detaille'],
    standing: ['toujours', 'jamais', 'desormais', 'dorenavant', 'a partir de maintenant', 'a chaque fois', 'chaque fois', 'a l avenir'],
    oneOff: ['pour l instant', 'pour le moment', 'cette fois', 'juste cette fois', 'pour cette fois'],
    negation: ['sans', 'pas d', 'pas de', 'aucun', 'aucune', 'n utilise pas', 'ne mets pas', 'pas un', 'pas une'],
    emoji: ['emoji*', 'emoticone*'],
    stop: ['le', 'la', 'les', 'de', 'des', 'et', 'est', 'que', 'pas', 'je', 'tu', 'vous', 'pour', 'une', 'un', 'ce', 'ca', 'qui', 'avec', 'dans', 'c', 'l', 'd', 'tes', 'trop', 'mais', 'fais', 'cette', 'elle', 'il', 'on', 'plus', 'fait', 'moi', 'mon', 'ma', 'sur', 'au', 'du', 'en', 'ne', 'y', 'a', 'tout', 'si', 'oui', 'non', 'juste', 'dis', 'donne', 'ou', 'quoi', 'pourquoi', 'comment', 'faire', 'peux', 'veux', 'j', 'qu', 'm', 't', 's', 'n'],
    chars: /[êîûœ]/,
    much: ['beaucoup', 'tant', 'autant', 'trop'],
    skip: ['zappe', 'saute', 'sans', 'arrete', 'arrête', 'assez de', 'pas besoin', 'oublie'],
    explain: ['explication*', 'expliquer', 'blabla', 'bla bla', 'baratin', 'theorie', 'detailler', 'détailler'],
    longform: ['roman', 'pave', 'dissertation', 'these', 'bible', 'livre', 'tartine', 'paragraphes'],
    text: ['texte', 'mots', 'paragraphes'],
    cancel: ['oublie', 'laisse tomber', 'annule', 'ignore', 'j annule', 'annul*'],
    noNeed: ['pas besoin', 'plus besoin', 'pas oblige', 't es pas oblige', 'pas necessaire'],
    again: ['de nouveau', 'a nouveau', 'maintenant', 'refaire', 'encore', 'desormais', 'dorenavant'],
    briefNoun: ['bref', 'breve', 'court', 'courte', 'concis', 'concise', 'regle'],
    answer: ['reponse*'],
    strong: ['moins de blabla plus de code', 'moins de texte plus de code', 'oui ou non', 'vais pas lire', 'en une ligne', 'en une phrase', 'droit au but'],
  },
  de: {
    name: 'German',
    brevity: ['kurz gesagt', 'kurzum', 'kurz und knapp', 'kurz und bundig', 'fasse dich kurz', 'fass dich kurz', 'halte dich kurz', 'halt dich kurz', 'kurzer bitte', 'kurzere antwort*', 'kurze antwort*', 'auf den punkt', 'komm zum punkt', 'komm auf den punkt', 'in einem satz', 'in einer zeile', 'in zwei satzen', 'weniger text', 'kein roman', 'keinen roman', 'keine romane', 'nur die antwort', 'kurz bitte', 'bitte kurz', 'knapper', 'kurz halten', 'kurzer fassen', 'zu viel text', 'textwand', 'weniger gelaber', 'weniger gerede', 'kein gelaber', 'lese ich nicht', 'les ich nicht', 'ich lese das nicht', 'ja oder nein', 'kurzer', 'kurz fassen', 'ohne erklarung', 'lass die erklarung', 'hor auf alles', 'hör auf alles', 'kurze version', 'fass zusammen in einem satz'],
    long: ['lang', 'lange', 'langer', 'langen', 'ausschweifend*', 'weitschweifig*', 'wortreich*', 'ellenlang*'],
    too: ['zu', 'viel zu', 'sehr', 'echt', 'mega', 'viel'],
    short: ['kurz*', 'knapp*', 'pragnant*', 'bundig*'],
    reply: ['antwort*', 'antworte*', 'nachricht*', 'erklarung*', 'erklar*', 'schreib*', 'text', 'texte'],
    code: ['funktion*', 'methode*', 'variable*', 'name', 'namen', 'code', 'datei*', 'klasse*', 'url*', 'link*', 'string*', 'liste*', 'array*', 'log', 'logs', 'logdatei*', 'tabelle*', 'spalte*', 'titel*', 'abfrage*', 'commit*', 'skript*', 'script*', 'komponente*', 'passwort*', 'video*', 'bild*', 'daten', 'zusammenfassung', 'fasse die', 'fasse das', 'fass die', 'fass das', 'abschnitt*', 'beschreibung*', 'feld*', 'zeichen', 'kommentar*', 'artikel*', 'test', 'tests'],
    detail: ['ausfuhrlich*', 'detailliert*', 'im detail', 'genau erklar*', 'grundlich*', 'schritt fur schritt', 'in der tiefe', 'alles erklaren', 'erklare alles', 'in aller ausfuhrlichkeit', 'in die tiefe', 'tiefgehend', 'haarklein', 'in ruhe erklar*', 'aushol*'],
    permission: ['kannst', 'darfst', 'ist okay', 'ist ok', 'passt', 'gerne', 'ruhig', 'in ordnung', 'okay', 'ok'],
    lift: ['du musst nicht mehr kurz', 'musst dich nicht kurz fassen', 'nicht mehr so kurz', 'du darfst ausfuhrlicher', 'du kannst ausfuhrlicher', 'darfst wieder langer', 'kannst wieder langer'],
    standing: ['immer', 'nie', 'niemals', 'ab jetzt', 'von nun an', 'ab sofort', 'jedes mal', 'jedesmal', 'kunftig', 'in zukunft', 'nie wieder', 'immer wenn', 'jedes mal wenn'],
    oneOff: ['vorerst', 'furs erste', 'diesmal', 'dieses mal', 'erstmal', 'erst mal', 'nur dieses mal'],
    negation: ['keine*', 'kein', 'ohne', 'nicht', 'lass die', 'lass das'],
    emoji: ['emoji*'],
    stop: ['der', 'die', 'das', 'und', 'ist', 'nicht', 'ich', 'du', 'bitte', 'mit', 'wie', 'was', 'ein', 'eine', 'zu', 'auf', 'es', 'mir', 'deine', 'mal', 'sind', 'den', 'dich', 'immer', 'kannst', 'dem', 'des', 'im', 'am', 'um', 'von', 'fur', 'auch', 'noch', 'schon', 'nur', 'aber', 'oder', 'wenn', 'dann', 'hier', 'da', 'wo', 'warum', 'sag', 'gib', 'mach', 'bin', 'hast', 'hab', 'kann', 'soll', 'jetzt', 'alles', 'einfach', 'alter'],
    chars: /[ßä]/,
    much: ['viel', 'so viel', 'zu viel'],
    skip: ['lass', 'ohne', 'hor auf', 'hör auf', 'spar dir', 'genug', 'skip', 'uberspring'],
    explain: ['erklarung*', 'erklaren', 'erklärungen', 'gelaber', 'gerede', 'theorie', 'ausschweif*', 'ausfuhrlich zu erklaren'],
    longform: ['roman', 'doktorarbeit', 'abhandlung', 'aufsatz', 'bibel', 'buch', 'romane', 'essay', 'textwand', 'wall of text'],
    text: ['text', 'worter', 'wörter', 'absatze'],
    cancel: ['vergiss', 'ignorier', 'streich', 'hebe auf', 'aufheben', 'aufgehoben', 'aufheb*', 'hebe die'],
    noNeed: ['musst nicht', 'brauchst nicht', 'nicht mehr', 'nicht notig', 'nicht nötig'],
    again: ['wieder', 'jetzt', 'ab jetzt', 'nun', 'wieder ok'],
    briefNoun: ['kurz', 'kurze', 'knapp', 'kurzfassen', 'kurz fassen', 'regel'],
    answer: ['antwort*'],
    strong: ['weniger gelaber mehr code', 'weniger text mehr code', 'ja oder nein', 'lese ich nicht', 'in einem satz', 'in einer zeile', 'auf den punkt'],
  },
  it: {
    name: 'Italian',
    brevity: ['in breve', 'in sintesi', 'brevemente', 'sii breve', 'sii conciso', 'sii concisa', 'piu corto', 'piu corta', 'risposta breve', 'risposte brevi', 'risposta corta', 'risposte corte', 'vai al punto', 'dritto al punto', 'al sodo', 'vai al sodo', 'in una riga', 'in una frase', 'in due frasi', 'meno testo', 'niente papiri', 'niente poemi', 'solo la risposta', 'taglia corto', 'fai breve', 'piu sintetico', 'piu sintetica', 'sii sintetico', 'meno chiacchiere', 'niente chiacchiere', 'non lo leggo', 'non leggo', 'si o no', 'accorcia', 'fai piu corto', 'senza spiegazione', 'smettila di spiegare', 'salta la spiegazione'],
    long: ['lung*', 'prolis*', 'verbos*', 'papiro*', 'poema*'],
    too: ['troppo', 'troppe', 'troppi', 'molto', 'davvero'],
    short: ['breve*', 'brevi', 'cort*', 'concis*', 'sintetic*', 'velocemente', 'veloce', 'rapidamente'],
    reply: ['rispost*', 'rispond*', 'messagg*', 'spiega*', 'spiegazion*', 'scriv*', 'testo', 'testi'],
    code: ['funzion*', 'metodo*', 'variabil*', 'nome', 'nomi', 'codice', 'file*', 'classe*', 'url*', 'link*', 'stringa*', 'lista*', 'array*', 'log', 'tabella*', 'colonna*', 'titolo*', 'test', 'commit*', 'script*', 'componente*', 'password*', 'video*', 'immagine*', 'dati', 'riassumi questo', 'riassumi il', 'riassunto del', 'riassunto di', 'sezione*', 'descrizione*', 'campo*', 'caratteri', 'commento*', 'articolo*', 'tests'],
    detail: ['dettagli*', 'dettaglio', 'approfondi*', 'in profondita', 'esaustiv*', 'passo passo', 'passo dopo passo', 'spiega tutto', 'dilungati'],
    permission: ['puoi', 'va bene', 'ok', 'tranquillo', 'tranquilla', 'vanno bene', 'bene'],
    lift: ['non serve essere breve', 'non devi essere breve', 'puoi dilungarti', 'non serve piu essere breve', 'puoi essere piu dettagliato', 'non devi piu essere breve'],
    standing: ['sempre', 'mai', 'd ora in poi', 'da ora in poi', 'da adesso in poi', 'ogni volta', 'in ogni risposta'],
    oneOff: ['per ora', 'per adesso', 'questa volta', 'stavolta', 'solo per questa volta'],
    negation: ['senza', 'niente', 'non usare', 'non mettere'],
    emoji: ['emoji*', 'emoticon*', 'faccine'],
    stop: ['il', 'lo', 'la', 'di', 'che', 'e', 'non', 'per', 'un', 'una', 'sono', 'con', 'mi', 'ti', 'questo', 'perche', 'come', 'piu', 'troppo', 'fammi', 'puoi', 'sei', 'gli', 'della', 'ma', 'se', 'ci', 'si', 'ho', 'hai', 'ha', 'del', 'al', 'nel', 'alla', 'dove', 'cosa', 'quando', 'tutto', 'solo', 'dimmi', 'dammi', 'fai', 'posso', 'voglio', 'ora', 'anche', 'gia', 'qui'],
    much: ['troppo', 'tanto', 'molto'],
    skip: ['salta', 'senza', 'smettila', 'basta', 'lascia stare', 'non serve'],
    explain: ['spiegazion*', 'spiegare', 'spiegando', 'chiacchiere', 'teoria', 'pippone', 'papiro'],
    longform: ['tema', 'papiro', 'poema', 'romanzo', 'tesi', 'bibbia', 'libro', 'enciclopedia', 'paragrafi'],
    text: ['testo', 'parole', 'paragrafi'],
    cancel: ['lascia stare', 'dimentica', 'ignora', 'annulla'],
    noNeed: ['non serve', 'non devi', 'non c e bisogno', 'non e necessario', 'non serve piu'],
    again: ['di nuovo', 'ora', 'adesso', 'tornare', 'torna', 'd ora in poi', 'ancora'],
    briefNoun: ['breve', 'brevita', 'corto', 'corta', 'conciso', 'concisa', 'regola'],
    answer: ['rispost*'],
    strong: ['meno chiacchiere piu codice', 'meno testo piu codice', 'si o no', 'non lo leggo', 'in una riga', 'in una frase', 'al sodo'],
  },
  nl: {
    name: 'Dutch',
    brevity: ['kortom', 'in het kort', 'kort gezegd', 'kort en bondig', 'hou het kort', 'houd het kort', 'wees beknopt', 'wees kort', 'korter graag', 'korter alsjeblieft', 'kort antwoord', 'korte antwoorden', 'ter zake', 'in een zin', 'in een regel', 'minder tekst', 'geen lap tekst', 'alleen het antwoord', 'kort graag', 'graag korter', 'beknopter', 'minder gelul', 'minder gepraat', 'geen gelul', 'ga ik niet lezen', 'lees ik niet', 'ja of nee', 'korter', 'inkorten', 'zonder uitleg', 'stop met uitleggen', 'sla de uitleg over'],
    long: ['lang', 'langere', 'lange', 'langer', 'langdradig*', 'breedsprakig*', 'ellenlang*'],
    too: ['te', 'veel te', 'erg', 'echt', 'veel'],
    short: ['kort*', 'beknopt*', 'bondig*', 'snel'],
    reply: ['antwoord*', 'bericht*', 'uitleg*', 'leg uit', 'schrijf*', 'tekst*', 'leg', 'uitleggen'],
    code: ['functie*', 'methode*', 'variabele*', 'naam', 'namen', 'code', 'bestand*', 'klasse*', 'url*', 'link*', 'string*', 'lijst*', 'array*', 'log', 'logs', 'logbestand*', 'tabel*', 'kolom*', 'titel*', 'query*', 'commit*', 'script*', 'component*', 'wachtwoord*', 'video*', 'afbeelding*', 'data', 'samenvatting', 'vat dit', 'vat de', 'sectie*', 'beschrijving*', 'veld*', 'tekens', 'opmerking*', 'samenvatting*', 'artikel*', 'test', 'tests'],
    detail: ['gedetailleerd*', 'in detail', 'uitgebreid*', 'grondig*', 'stap voor stap', 'diepgaand*', 'leg alles uit', 'diep op in', 'ga diep', 'diepgaand', 'tot in detail', 'uitweid*'],
    permission: ['mag', 'kan', 'prima', 'oke', 'is goed'],
    lift: ['hoeft niet kort', 'je hoeft niet meer kort', 'mag weer uitgebreid', 'mag weer langer', 'je mag uitgebreider', 'hoeft niet meer beknopt'],
    standing: ['altijd', 'nooit', 'vanaf nu', 'voortaan', 'elke keer', 'iedere keer', 'in elk antwoord'],
    oneOff: ['voorlopig', 'voor nu', 'deze keer', 'dit keer', 'alleen deze keer'],
    negation: ['geen', 'zonder', 'gebruik geen'],
    emoji: ['emoji*'],
    stop: ['de', 'het', 'een', 'en', 'van', 'is', 'niet', 'ik', 'je', 'dat', 'wat', 'op', 'met', 'voor', 'maar', 'dit', 'kun', 'graag', 'zijn', 'jouw', 'te', 'mij', 'geef', 'alsjeblieft', 'hoe', 'in', 'om', 'aan', 'bij', 'als', 'ook', 'nog', 'al', 'er', 'zo', 'jij', 'me', 'waarom', 'waar', 'gewoon', 'even', 'kan', 'mag', 'zeg', 'doe', 'heb', 'ben'],
    much: ['veel', 'zoveel'],
    skip: ['sla', 'zonder', 'stop met', 'genoeg', 'hoeft niet'],
    explain: ['uitleg*', 'uitleggen', 'gelul', 'gepraat', 'theorie', 'gezever'],
    longform: ['opstel', 'scriptie', 'roman', 'boek', 'bijbel', 'essay', 'proefschrift', 'lap tekst', 'alinea s'],
    text: ['tekst', 'woorden', 'alineas'],
    cancel: ['vergeet', 'laat maar', 'negeer', 'schrap', 'vervalt', 'vervallen', 'laat vallen'],
    noNeed: ['hoeft niet', 'niet meer', 'niet nodig', 'hoeft niet meer'],
    again: ['weer', 'nu', 'vanaf nu', 'opnieuw', 'voortaan'],
    briefNoun: ['kort', 'korte', 'beknopt', 'bondig', 'regel'],
    answer: ['antwoord*'],
    strong: ['minder gelul meer code', 'minder tekst meer code', 'ja of nee', 'ga ik niet lezen', 'in een zin', 'in een regel', 'to the point'],
  },
  pl: {
    name: 'Polish',
    brevity: ['w skrocie', 'krotko mowiac', 'krotko', 'zwiezle', 'w kilku slowach', 'pisz krocej', 'krocej', 'krotsze odpowiedzi', 'krotka odpowiedz', 'do rzeczy', 'konkretnie', 'w jednym zdaniu', 'w jednej linii', 'mniej tekstu', 'bez lania wody', 'tylko odpowiedz', 'zwiezlej', 'nie pisz eseju', 'za duzo tekstu', 'mniej gadania', 'bez gadania', 'nie przeczytam', 'nie bede czytac', 'tak czy nie', 'skroc', 'skroc to', 'krocej prosze', 'bez wyjasnien', 'przestan tlumaczyc', 'pomin wyjasnienia'],
    long: ['dlug*', 'rozwlekl*', 'przydlug*', 'rozpisuj*', 'dluz*', 'dluzsz*'],
    too: ['za', 'zbyt', 'bardzo', 'strasznie', 'mega'],
    short: ['krot*', 'krocej', 'zwiezl*', 'szybko'],
    reply: ['odpowied*', 'odpowiadaj', 'wiadomos*', 'wyjasni*', 'wyjasnie*', 'pisz*', 'napisz*', 'tekst*'],
    code: ['funkcj*', 'metod*', 'zmienn*', 'nazw*', 'kod', 'kodu', 'plik*', 'klas*', 'url*', 'link*', 'string*', 'list*', 'tablic*', 'log', 'logi', 'logow', 'tabel*', 'kolumn*', 'tytul*', 'zapytani*', 'commit*', 'skrypt*', 'komponent*', 'hasl*', 'wideo', 'obraz*', 'dane', 'danych', 'podsumuj ten', 'podsumuj te', 'podsumowanie', 'sekcj*', 'opis*', 'pole', 'pola', 'znak*', 'komentarz*', 'artykul*', 'test', 'tests'],
    detail: ['szczegol*', 'rozpisyw*', 'rozpisz*', 'dokladnie', 'wyczerpujac*', 'krok po kroku', 'doglebnie', 'wyjasnij wszystko', 'dokladn*', 'szczegolowo', 'glebiej'],
    permission: ['mozesz', 'moze', 'w porzadku', 'ok', 'spoko', 'sa w porzadku', 'sa ok'],
    lift: ['nie musisz pisac krotko', 'nie musisz juz pisac krotko', 'mozesz pisac dluzej', 'mozesz sie rozpisac', 'nie musisz byc zwiezly'],
    standing: ['zawsze', 'nigdy', 'od teraz', 'od tej pory', 'za kazdym razem', 'odtad', 'w kazdej odpowiedzi'],
    oneOff: ['na razie', 'tym razem', 'tylko tym razem', 'poki co'],
    negation: ['bez', 'bez wypracowania', 'nie uzywaj', 'zadnych'],
    emoji: ['emoji', 'emotk*', 'emotikon*'],
    stop: ['i', 'w', 'nie', 'na', 'to', 'jest', 'sie', 'ze', 'z', 'do', 'co', 'jak', 'czy', 'prosze', 'mi', 'ten', 'ta', 'za', 'tak', 'masz', 'twoje', 'mnie', 'dla', 'juz', 'o', 'po', 'od', 'ale', 'tylko', 'teraz', 'gdzie', 'dlaczego', 'czemu', 'daj', 'powiedz', 'zrob', 'mam', 'moge', 'chce', 'tu', 'no', 'xd'],
    chars: /[łąęśźżń]/,
    much: ['duzo', 'tyle', 'za duzo'],
    skip: ['pomin', 'bez', 'przestan', 'dosc', 'nie musisz', 'zapomnij'],
    explain: ['wyjasnien*', 'wyjasniac', 'tlumaczyc', 'tlumaczenie', 'gadania', 'gadanie', 'teori*', 'wykład', 'wyklad'],
    longform: ['wypracowan*', 'epopeja', 'esej', 'ksiazka', 'powiesc', 'referat', 'elaborat', 'biblia', 'praca magisterska'],
    text: ['tekst', 'tekstu', 'slow', 'słów'],
    cancel: ['zapomnij', 'olej', 'anuluj', 'zignoruj', 'odwoluj*', 'odwolaj*'],
    noNeed: ['nie musisz', 'nie trzeba', 'juz nie musisz', 'nie potrzeba'],
    again: ['znowu', 'znow', 'od teraz', 'teraz', 'ponownie', 'juz'],
    briefNoun: ['krotko', 'krotkie', 'zwiezle', 'zwiezly', 'regul*'],
    answer: ['odpowied*'],
    strong: ['mniej gadania wiecej kodu', 'mniej tekstu wiecej kodu', 'tak czy nie', 'nie przeczytam', 'jednym zdaniem', 'w jednym zdaniu', 'w jednej linii', 'do rzeczy'],
  },
  ru: {
    name: 'Russian',
    brevity: ['короче', 'вкратце', 'кратко', 'покороче', 'коротко', 'в двух словах', 'в двух предложениях', 'в одном предложении', 'одним предложением', 'в одну строку', 'по делу', 'по существу', 'без воды', 'меньше текста', 'только ответ', 'лаконичнее', 'сжато', 'не пиши простыню', 'не пиши простыни', 'многабукв', 'много букв', 'слишком много текста', 'меньше воды', 'меньше слов', 'не буду читать', 'не стану читать', 'да или нет', 'сократи', 'покороче пожалуйста', 'без объяснений', 'хватит объяснять', 'пропусти объяснения', 'многабукаф', 'многа букаф', 'лень читать'],
    long: ['длинн*', 'длинно', 'многословн*', 'простын*', 'длиннющ*'],
    too: ['слишком', 'очень', 'чересчур', 'жутко', 'больно'],
    short: ['коротк*', 'короче', 'кратк*', 'лаконичн*', 'сжат*', 'быстро'],
    reply: ['ответ*', 'отвеча*', 'сообщени*', 'объясн*', 'пиши', 'напиши', 'текст*', 'расписыва*', 'распиши'],
    code: ['функци*', 'метод*', 'переменн*', 'имя', 'имени', 'названи*', 'код', 'кода', 'коде', 'файл*', 'класс*', 'url*', 'ссылк*', 'список', 'списк*', 'массив*', 'лог', 'логи', 'логов', 'лога', 'таблиц*', 'столб*', 'колонк*', 'заголов*', 'тест*', 'запрос*', 'коммит*', 'скрипт*', 'компонент*', 'парол*', 'видео', 'картинк*', 'данные', 'данных', 'сократи этот', 'сократи эту', 'перескажи', 'резюмируй', 'раздел*', 'описани*', 'поле', 'символ*', 'комментари*', 'стать*'],
    detail: ['подробн*', 'детальн*', 'в деталях', 'развернут*', 'развёрнут*', 'основательн*', 'по шагам', 'шаг за шагом', 'объясни все', 'объясни всё', 'пошагово', 'досконально', 'разбери', 'разжуй', 'по полочкам', 'расписыва*', 'распиши'],
    permission: ['можешь', 'можно', 'нормально', 'ок', 'окей', 'норм'],
    lift: ['можно подробнее', 'не надо так коротко', 'больше не нужно коротко', 'можешь писать подробнее', 'можешь подробнее', 'можно длиннее', 'не обязательно коротко'],
    standing: ['всегда', 'никогда', 'отныне', 'впредь', 'с этого момента', 'теперь всегда', 'каждый раз', 'больше никогда', 'дальше всегда'],
    oneOff: ['пока что', 'на этот раз', 'в этот раз', 'только сейчас'],
    negation: ['без', 'не используй', 'не ставь', 'не добавляй', 'никаких'],
    emoji: ['эмодзи', 'смайл*', 'эмоджи', 'смайлик*'],
    stop: ['и', 'в', 'не', 'на', 'что', 'это', 'как', 'я', 'ты', 'с', 'по', 'мне', 'а', 'но', 'для', 'же', 'так', 'пожалуйста', 'он', 'она', 'мы', 'вы', 'они', 'у', 'из', 'за', 'от', 'до', 'то', 'все', 'всё', 'уже', 'еще', 'ещё', 'тут', 'там', 'где', 'почему', 'зачем', 'дай', 'скажи', 'сделай', 'можно', 'надо', 'блин', 'плиз'],
    much: ['много', 'столько', 'слишком много'],
    skip: ['пропусти', 'без', 'хватит', 'не надо', 'не нужно', 'забудь', 'годи'],
    explain: ['объяснени*', 'объяснять', 'разжевыв*', 'разжёвыв*', 'воды', 'теори*', 'лекци*'],
    longform: ['простын*', 'диссертаци*', 'поэм*', 'роман*', 'сочинени*', 'лекци*', 'трактат*', 'библи*', 'книг*'],
    text: ['текст*', 'букв', 'слов'],
    cancel: ['забудь', 'отмени', 'игнорируй', 'проехали', 'отменя*', 'отменил*'],
    noNeed: ['не надо', 'не нужно', 'не обязательно', 'больше не'],
    again: ['снова', 'опять', 'теперь', 'отныне', 'с этого момента', 'вновь'],
    briefNoun: ['краткост*', 'коротк*', 'лаконичн*', 'правил*'],
    answer: ['ответ*'],
    strong: ['меньше воды больше кода', 'меньше текста больше кода', 'да или нет', 'не буду читать', 'одной строкой', 'одним предложением', 'по делу'],
  },
  uk: {
    name: 'Ukrainian',
    brevity: ['коротше', 'коротко', 'стисло', 'коротко кажучи', 'у двох словах', 'в двох словах', 'одним реченням', 'в одному реченні', 'по суті', 'без води', 'менше тексту', 'лише відповідь', 'тільки відповідь', 'лаконічніше', 'не пиши простирадло', 'забагато тексту', 'менше води', 'менше слів', 'не буду читати', 'не читатиму', 'так чи ні', 'скороти', 'коротше будь ласка', 'без пояснень', 'годі пояснювати', 'пропусти пояснення', 'задовго'],
    long: ['довг*', 'довго', 'багатослівн*', 'простирадл*'],
    too: ['занадто', 'надто', 'дуже', 'забагато'],
    short: ['коротк*', 'коротш*', 'коротше', 'стисл*', 'лаконічн*', 'швидко'],
    reply: ['відповід*', 'повідомлен*', 'поясн*', 'пиши', 'напиши', 'текст*', 'розписуват*', 'розпиши'],
    code: ['функці*', 'метод*', 'змінн*', 'ім я', 'назв*', 'код', 'коду', 'файл*', 'клас*', 'url*', 'посиланн*', 'список', 'списк*', 'масив*', 'лог', 'логи', 'логів', 'таблиц*', 'стовп*', 'колонк*', 'заголов*', 'тест*', 'запит*', 'коміт*', 'скрипт*', 'компонент*', 'парол*', 'відео', 'зображен*', 'дані', 'даних', 'скороти цей', 'скороти цю', 'підсумуй', 'розділ*', 'опис*', 'поле', 'символ*', 'коментар*', 'статт*'],
    detail: ['детальн*', 'докладн*', 'в деталях', 'розгорнут*', 'крок за кроком', 'поясни все', 'ґрунтовно', 'грунтовно', 'покроково', 'по поличках', 'розписуват*', 'розпиши'],
    permission: ['можеш', 'можна', 'нормально', 'ок', 'норм'],
    lift: ['можна детальніше', 'не треба так коротко', 'більше не треба коротко', 'можеш писати детальніше', 'можеш детальніше', 'можна довше'],
    standing: ['завжди', 'ніколи', 'відтепер', 'надалі', 'з цього моменту', 'щоразу', 'кожного разу', 'від сьогодні', 'з сьогодні', 'відсьогодні'],
    oneOff: ['поки що', 'цього разу', 'на цей раз', 'лише зараз'],
    negation: ['без', 'не використовуй', 'не став', 'не додавай', 'жодних'],
    emoji: ['емодзі', 'смайл*', 'емоджі', 'смайлик*'],
    stop: ['і', 'в', 'не', 'на', 'що', 'це', 'як', 'я', 'ти', 'з', 'по', 'мені', 'а', 'але', 'для', 'та', 'будь ласка', 'він', 'вона', 'ми', 'ви', 'вони', 'у', 'із', 'за', 'від', 'до', 'то', 'все', 'вже', 'ще', 'тут', 'там', 'де', 'чому', 'дай', 'скажи', 'зроби', 'можна', 'треба', 'будь', 'ласка'],
    much: ['багато', 'стільки', 'забагато'],
    skip: ['пропусти', 'без', 'годі', 'не треба', 'забудь'],
    explain: ['пояснен*', 'пояснювати', 'розжовуват*', 'води', 'теорі*', 'лекці*'],
    longform: ['простирадл*', 'дисертаці*', 'поем*', 'роман*', 'твір', 'лекці*', 'трактат*', 'книг*'],
    text: ['текст*', 'букв', 'слів'],
    cancel: ['забудь', 'скасуй', 'ігноруй', 'проїхали', 'скасов*'],
    noNeed: ['не треба', 'не потрібно', 'не обовязково', 'більше не'],
    again: ['знову', 'тепер', 'відтепер', 'з цього моменту'],
    briefNoun: ['стислість', 'стисло', 'коротк*', 'лаконічн*', 'правил*'],
    answer: ['відповід*'],
    strong: ['менше води більше коду', 'менше тексту більше коду', 'так чи ні', 'не буду читати', 'одним рядком', 'одним реченням', 'по суті'],
  },
  zh: {
    name: 'Chinese',
    brevity: ['简短', '简洁', '简单点', '简单说', '简而言之', '长话短说', '一句话', '两句话', '说重点', '讲重点', '直接说', '太长了', '太长', '太啰嗦', '太罗嗦', '啰嗦', '少写点', '少说点', '短一点', '短点', '精简', '只要答案', '只给答案', '簡短', '簡潔', '太長', '囉嗦', '短一點', '說重點', '講重點', '别写那么多', '別寫那麼多', '不要长篇大论', '不要長篇大論', '长篇大论', '言简意赅', '概括一下回答', '少说废话', '少废话', '废话少说', '不看', '看不下去', '是或否', '是不是', '缩短', '别解释', '不用解释', '别写小作文', '小作文', '直接给我', '字太多', '要点'],
    long: ['长', '長', '啰嗦', '囉嗦', '冗长', '冗長'],
    too: ['太', '过于', '過於', '有点'],
    short: ['短', '简洁', '簡潔', '精简', '精簡', '简单', '簡單'],
    reply: ['回答', '回复', '回覆', '答案', '解释', '解釋', '写', '寫'],
    code: ['函数', '函數', '方法', '变量', '變數', '名字', '名称', '名稱', '代码', '代碼', '文件', '檔案', '类名', '网址', '網址', '链接', '連結', '字符串', '列表', '数组', '陣列', '日志', '日誌', '表格', '标题', '標題', '测试', '測試', '查询', '查詢', '提交', '脚本', '腳本', '组件', '組件', '密码', '密碼', '视频', '图片', '数据', '數據', '总结一下这个', '總結一下這個', '描述', '章节', '章節', '提交信息', '文档', '文檔', 'readme', 'pr'],
    detail: ['详细', '詳細', '详尽', '詳盡', '具体讲', '具體講', '展开说', '展開說', '深入', '一步一步', '逐步', '仔细讲', '仔細講', '讲透', '講透', '讲清楚', '講清楚', '掰开揉碎', '透彻'],
    permission: ['可以', '没关系', '沒關係', '没问题', '沒問題'],
    lift: ['不用简短', '不用那么简短', '可以详细', '可以写长', '不用太简洁', '不需要简短', '可以写详细'],
    standing: ['总是', '總是', '始终', '始終', '永远', '永遠', '以后', '以後', '从现在开始', '從現在開始', '每次', '不要再', '别再', '別再', '一直', '绝对', '絕對', '任何时候'],
    oneOff: ['暂时', '暫時', '这次', '這次', '这一次'],
    negation: ['不要', '别', '別', '不用', '禁止', '去掉'],
    emoji: ['表情', 'emoji', '表情符号', '表情符號'],
    much: ['多', '太多'],
    skip: ['别', '不用', '跳过', '省略', '少'],
    explain: ['解释', '解釋', '废话', '廢話', '理论'],
    longform: ['小作文', '论文', '論文', '长篇', '長篇', '作文', '论述'],
    text: ['字', '文字'],
    cancel: ['忘掉', '取消', '算了', '不用管', '撤回'],
    noNeed: ['不用', '不需要', '不必', '用不着'],
    again: ['再', '又', '现在', '現在', '以后', '以後', '恢复', '恢復'],
    briefNoun: ['简洁', '簡潔', '简短', '簡短', '短', '规则', '規則'],
    answer: ['回答', '回复', '回覆', '答案'],
    strong: ['少说废话多写代码', '少说话多写代码', '是或否', '是还是否', '一句话说', '字太多', '不看'],
  },
  ja: {
    name: 'Japanese',
    brevity: ['簡潔に', '手短に', '短く', '要点だけ', '要点を', '結論だけ', '結論から', '一言で', '一文で', '一行で', '長すぎ', '長過ぎ', '冗長', 'くどい', '答えだけ', '短めに', '端的に', '簡潔な', '長文やめて', '長文は', '三行で', '3行で', '要するに', 'つまり何', '読まない', '読む気しない', '読めない', 'はいかいいえ', 'はい か いいえ', '説明いらない', '説明はいいから', '説明不要', '能書きはいい', '長っ', '手短', '短めで', 'ざっくり'],
    long: ['長', '冗長', 'くどい'],
    too: ['すぎ', '過ぎ'],
    short: ['短', '簡潔', '手短'],
    reply: ['回答', '返事', '返答', '答え', '説明', '書', '文章', 'メッセージ'],
    code: ['関数', 'メソッド', '変数', '名前', 'コード', 'ファイル', '行数', 'クラス', 'url', 'リンク', '文字列', 'リスト', '配列', 'ログ', 'テーブル', 'カラム', 'タイトル', 'テスト', 'クエリ', 'コミット', 'スクリプト', 'コンポーネント', 'パスワード', '動画', '画像', 'データ', 'pr', 'readme', 'ドキュメント', '説明文', 'セクション', 'コミットメッセージ'],
    detail: ['詳しく', '詳細', '丁寧に', '具体的に', '徹底的', 'ステップバイステップ', '順を追って', '一から', '掘り下げ', 'しっかり説明', 'ちゃんと説明', '詳細に', '丁寧', '詳し'],
    permission: ['いい', '大丈夫', 'かまわない', '構わない', 'ok', 'いいよ'],
    lift: ['短くしなくていい', '簡潔じゃなくていい', '詳しく書いていい', '長くていい', '長くても大丈夫', '短くなくていい'],
    standing: ['常に', 'いつも', '必ず', '絶対', '二度と', '今後', 'これから', '毎回', '以降', 'たびに', '度に', '都度'],
    oneOff: ['とりあえず', '今回は', '今回だけ', '今は'],
    negation: ['使わない', '使わないで', 'なしで', '不要', 'やめて', '禁止'],
    emoji: ['絵文字', 'emoji', 'エモジ'],
    much: ['多', '多すぎ'],
    skip: ['いらない', 'いいから', '不要', '省いて', '飛ばして', 'なしで'],
    explain: ['説明', '解説', '能書き', '理屈'],
    longform: ['作文', '論文', '長文', '小説', 'レポート'],
    text: ['文章', '文字', 'テキスト'],
    cancel: ['解除', '取り消', '忘れて', 'なしで', '撤回', 'やめて'],
    noNeed: ['しなくていい', 'なくていい', 'しなくても', '必要ない', 'いらない'],
    again: ['もう', '戻して', '戻していい', 'これから', 'また'],
    briefNoun: ['簡潔', '短く', '短め', '手短', 'ルール'],
    answer: ['回答', '返事', '返答', '答え'],
    strong: ['能書きはいいからコード', '説明はいいからコード', 'はいかいいえ', '一言で', '一行で', '読む気しない'],
  },
  ko: {
    name: 'Korean',
    brevity: ['짧게', '간단히', '간단하게', '간결하게', '요약해서', '요점만', '핵심만', '한 줄로', '한줄로', '한 문장으로', '너무 길어', '너무 길', '길게 쓰지', '장황', '답만', '결론만', '짧은 답', '짧게 답', '세 줄로', '세줄로', '말 말고', '말고 코드', '안 읽', '안읽', '예 아니오', '예/아니오', '네 아니오', '설명 필요없', '설명 빼고', '설명 없이', '줄여', '줄여줘', '짧게 줄여'],
    long: ['길어', '길게', '길다', '장황', '긴 답변', '긴 대답', '긴'],
    too: ['너무', '지나치게', '넘'],
    short: ['짧', '간결', '간단'],
    reply: ['답변', '대답', '답', '설명', '글', '메시지', '써', '작성'],
    code: ['함수', '메서드', '메소드', '변수', '이름', '코드', '파일', '클래스', 'url', '링크', '문자열', '리스트', '배열', '로그', '테이블', '컬럼', '제목', '테스트', '쿼리', '커밋', '스크립트', '컴포넌트', '비밀번호', '영상', '이미지', '데이터', 'pr', 'readme', '섹션', '문서', '설명문', '커밋 메시지'],
    detail: ['자세히', '자세하게', '상세', '상세히', '구체적으로', '단계별로', '깊이', '꼼꼼히', '파고들어', '꼼꼼하게', '깊게', '깊이 있게'],
    permission: ['돼', '됩니다', '괜찮', '좋아'],
    lift: ['짧게 안 써도', '짧게 쓸 필요 없', '길게 써도', '자세히 써도', '짧지 않아도'],
    standing: ['항상', '절대', '앞으로', '다시는', '매번', '언제나', '때마다', '마다', '언제든'],
    oneOff: ['일단', '이번에는', '이번만', '지금은'],
    negation: ['쓰지 마', '사용하지 마', '없이', '빼고', '넣지 마'],
    emoji: ['이모지', '이모티콘', 'emoji'],
    much: ['많', '너무 많'],
    skip: ['빼고', '없이', '필요없', '말고', '생략', '안해도', '안 해도'],
    explain: ['설명', '말', '이론', '강의'],
    longform: ['논문', '소설', '에세이', '작문', '장문', '책'],
    text: ['글', '텍스트', '글자'],
    cancel: ['해제', '취소', '잊어', '무시'],
    noNeed: ['안 해도', '않아도', '필요 없', '안해도'],
    again: ['다시', '이제', '앞으로', '돌아가', '지금부터', '이제부터'],
    briefNoun: ['간결', '짧게', '짧은', '규칙'],
    answer: ['답변', '대답'],
    strong: ['말 말고 코드', '설명 말고 코드', '예 아니오', '네 아니오', '한 줄로', '한줄로', '안 읽'],
  },
  hi: {
    name: 'Hindi',
    brevity: ['संक्षेप में', 'संक्षिप्त', 'छोटा जवाब', 'छोटे जवाब', 'छोटा करके', 'कम शब्दों में', 'एक लाइन में', 'एक वाक्य में', 'सीधे बताओ', 'सीधा बताओ', 'सिर्फ जवाब', 'बहुत लंबा', 'ज़्यादा लंबा', 'ज्यादा लंबा', 'short mein', 'short me', 'chhota likho', 'chota likho', 'ek line me', 'ek line mein', 'seedha batao', 'sidha batao', 'bahut lamba', 'zyada lamba', 'kam shabdon', 'short mai', 'chhota rakho', 'chota rakho', 'point pe aao', 'point par aao', 'sirf answer', 'bas answer', 'संक्षेप', 'kam bolo', 'kam likho', 'nahi padhunga', 'nahi padhungi', 'nahi padh', 'haan ya na', 'haan ya nahi', 'explanation chhodo', 'explanation mat do', 'mudde ki baat', 'मुद्दे की बात', 'निबंध मत', 'पढ़ूंगा नहीं', 'नहीं पढ़ूंगा', 'हां या ना', 'हाँ या ना', 'छोटा करो'],
    long: ['लंबा', 'लम्बा', 'लंबे', 'लंबी', 'lamba', 'lambe', 'lambi', 'long'],
    too: ['बहुत', 'ज़्यादा', 'ज्यादा', 'bahut', 'zyada', 'jyada', 'too'],
    short: ['छोटा', 'छोटे', 'छोटी', 'संक्षिप्त', 'chhota', 'chota', 'chhote', 'chote', 'short'],
    reply: ['जवाब', 'उत्तर', 'लिखो', 'लिखें', 'बताओ', 'समझाओ', 'jawab', 'likho', 'batao', 'samjhao', 'answer', 'reply', 'answers'],
    code: ['फ़ंक्शन', 'फंक्शन', 'वेरिएबल', 'नाम', 'कोड', 'फ़ाइल', 'फाइल', 'function', 'variable', 'code', 'file', 'naam', 'log', 'url', 'section', 'description'],
    detail: ['विस्तार से', 'विस्तृत', 'डिटेल में', 'detail me', 'detail mein', 'vistar se', 'vistaar se', 'poora samjhao', 'पूरा समझाओ', 'step by step', 'detail mai', 'गहराई से', 'gehrai se', 'gahrai se', 'khul ke'],
    permission: ['सकते हो', 'सकते', 'चलेगा', 'ठीक है', 'sakte ho', 'chalega', 'theek hai', 'thik hai', 'theek hain'],
    lift: ['छोटा लिखने की ज़रूरत नहीं', 'chhota likhne ki zarurat nahi', 'lamba likh sakte ho', 'लंबा लिख सकते हो', 'detail me likh sakte ho'],
    standing: ['हमेशा', 'कभी नहीं', 'कभी भी', 'आगे से', 'अब से', 'हर बार', 'hamesha', 'kabhi nahi', 'kabhi bhi', 'aage se', 'ab se', 'har baar', 'kabhi', 'कभी'],
    oneOff: ['अभी के लिए', 'इस बार', 'abhi ke liye', 'is baar', 'filhal', 'फिलहाल'],
    negation: ['मत', 'बिना', 'mat', 'bina', 'nahi'],
    emoji: ['इमोजी', 'emoji'],
    stop: ['hai', 'ho', 'kya', 'nahi', 'mein', 'ko', 'ka', 'ki', 'se', 'aur', 'yeh', 'ye', 'woh', 'karo', 'kaise', 'bhai', 'yaar', 'mujhe', 'kar', 'hoga', 'tum', 'aap', 'bata', 'batao', 'bhi', 'sab', 'kuch', 'yahan', 'wahan', 'kyun', 'kyon', 'abhi', 'ab', 'hi', 'na', 'toh', 'to', 'raha', 'rahi', 'hu', 'hoon'],
    much: ['zyada', 'itna', 'bahut', 'ज़्यादा', 'इतना'],
    skip: ['chhodo', 'mat', 'bina', 'skip', 'छोड़ो', 'मत', 'बिना', 'zarurat nahi', 'ज़रूरत नहीं', 'जरूरत नहीं'],
    explain: ['explanation', 'samjhana', 'samjhao', 'gyan', 'lecture', 'समझाना', 'समझाने', 'ज्ञान'],
    longform: ['ramayan', 'mahabharat', 'nibandh', 'essay', 'kitab', 'रामायण', 'निबंध', 'किताब', 'महाभारत'],
    text: ['text', 'likha', 'टेक्स्ट', 'लिखा'],
    cancel: ['bhool jao', 'chhodo', 'cancel', 'भूल जाओ', 'रद्द'],
    noNeed: ['zarurat nahi', 'zaroorat nahi', 'ज़रूरत नहीं', 'जरूरत नहीं'],
    again: ['ab', 'phir se', 'aage se', 'dobara', 'अब', 'फिर से', 'आगे से'],
    briefNoun: ['short', 'chhota', 'chota', 'छोटा', 'संक्षिप्त', 'rule'],
    answer: ['jawab', 'जवाब', 'answer', 'reply'],
    strong: ['kam bolo zyada code', 'kam bolo', 'haan ya na', 'haan ya nahi', 'ek line me', 'ek line mein', 'nahi padhunga', 'हां या ना', 'हाँ या ना'],
  },
  id: {
    name: 'Indonesian',
    brevity: ['singkat saja', 'singkatnya', 'secara singkat', 'jawab singkat', 'jawaban singkat', 'lebih singkat', 'ringkas', 'ringkasnya', 'langsung ke intinya', 'langsung ke inti', 'intinya saja', 'dalam satu kalimat', 'satu kalimat', 'satu baris', 'jangan panjang', 'jangan panjang panjang', 'jangan bertele tele', 'kurangi teks', 'jawabannya saja', 'kepanjangan', 'singkat aja', 'pendek aja', 'to the point aja', 'gak usah panjang', 'nggak usah panjang', 'ga usah panjang', 'males baca', 'gak baca', 'ga baca', 'nggak baca', 'kebanyakan teks', 'iya atau nggak', 'iya atau tidak', 'ya atau tidak', 'singkatin', 'persingkat', 'skip penjelasan', 'gak usah dijelasin', 'ga usah dijelasin', 'tanpa penjelasan', 'kurangin ngomong', 'langsung aja'],
    long: ['panjang', 'bertele*', 'kepanjangan'],
    too: ['terlalu', 'banget', 'sangat'],
    short: ['singkat*', 'pendek*', 'ringkas*', 'padat', 'cepat'],
    reply: ['jawab*', 'balas*', 'pesan*', 'jelaskan', 'penjelasan*', 'tulis*', 'teks*', 'jelasin'],
    code: ['fungsi*', 'metode*', 'variabel*', 'nama*', 'kode*', 'file*', 'baris kode', 'kelas*', 'url*', 'tautan*', 'link*', 'string*', 'daftar*', 'array*', 'log', 'tabel*', 'kolom*', 'judul*', 'tes', 'kueri*', 'query*', 'commit*', 'skrip*', 'script*', 'komponen*', 'kata sandi', 'password*', 'video*', 'gambar*', 'data', 'rangkum file', 'ringkasan dari', 'bagian', 'deskripsi*', 'test', 'tests'],
    detail: ['detail*', 'rinci*', 'mendetail', 'secara mendalam', 'mendalam', 'langkah demi langkah', 'jelaskan semuanya', 'selengkapnya', 'jelasin lengkap', 'secara lengkap', 'penjelasan lengkap'],
    permission: ['boleh', 'bisa', 'tidak apa apa', 'gak apa apa', 'oke'],
    lift: ['tidak perlu singkat', 'gak perlu singkat', 'nggak perlu singkat', 'boleh panjang', 'boleh lebih panjang', 'boleh detail', 'tidak usah singkat'],
    standing: ['selalu', 'jangan pernah', 'tidak pernah', 'mulai sekarang', 'setiap kali', 'seterusnya', 'mulai saat ini', 'ke depannya', 'ke depan', 'tiap kali', 'tiap'],
    oneOff: ['untuk sekarang', 'kali ini', 'sementara ini', 'untuk saat ini'],
    negation: ['tanpa', 'jangan', 'jangan pakai', 'gak usah pakai'],
    emoji: ['emoji*', 'emotikon*'],
    stop: ['yang', 'dan', 'di', 'ini', 'itu', 'tidak', 'saya', 'kamu', 'ke', 'untuk', 'dengan', 'apa', 'ada', 'bisa', 'jangan', 'tolong', 'aja', 'saja', 'gak', 'nggak', 'dong', 'banget', 'lagi', 'aku', 'gue', 'gw', 'lo', 'nya', 'sih', 'deh', 'kok', 'udah', 'belum', 'kenapa', 'gimana', 'dimana', 'mana', 'kasih', 'bikin', 'pake', 'pakai', 'wkwk', 'ya', 'iya', 'ga'],
    much: ['banyak', 'kebanyakan'],
    skip: ['skip', 'gak usah', 'ga usah', 'nggak usah', 'tanpa', 'berhenti'],
    explain: ['penjelasan*', 'dijelasin', 'jelasin', 'ngomong', 'teori', 'ceramah'],
    longform: ['esai', 'skripsi', 'novel', 'buku', 'makalah', 'tesis', 'kitab'],
    text: ['teks', 'tulisan', 'kata'],
    cancel: ['lupain', 'lupakan', 'batalin', 'batalkan', 'abaikan', 'dibatalin', 'dibatalkan'],
    noNeed: ['gak perlu', 'ga perlu', 'nggak perlu', 'tidak perlu', 'gak usah', 'tidak usah'],
    again: ['lagi', 'sekarang', 'mulai sekarang', 'ke depannya', 'balik'],
    briefNoun: ['singkat', 'ringkas', 'pendek', 'aturan'],
    answer: ['jawab*', 'balasan'],
    strong: ['kurangin ngomong perbanyak kode', 'kurangi ngomong', 'iya atau nggak', 'iya atau tidak', 'ya atau tidak', 'satu kalimat', 'satu baris', 'males baca'],
  },
  vi: {
    name: 'Vietnamese',
    brevity: ['ngan gon', 'noi ngan', 'tra loi ngan', 'viet ngan', 'tom lai', 'ngan thoi', 'ngan hon', 'di thang vao van de', 'vao thang van de', 'vao van de', 'mot cau', 'mot dong', 'dai qua', 'qua dai', 'dai dong', 'it chu', 'chi can cau tra loi', 'xuc tich', 'ngan lai', 'it noi', 'khong doc', 'doc khong noi', 'khong doc noi', 'co hay khong', 'co hoac khong', 'bo qua phan giai thich', 'khoi giai thich', 'dung giai thich', 'viet ngan lai', 'rut gon'],
    long: ['dai'],
    too: ['qua', 'rat', 'lam'],
    short: ['ngan'],
    reply: ['tra loi', 'cau tra loi', 'viet', 'giai thich', 'tin nhan'],
    code: ['ham', 'phuong thuc', 'bien', 'ten', 'ma nguon', 'code', 'tep', 'file', 'dong code', 'lop', 'url', 'lien ket', 'chuoi', 'danh sach', 'mang', 'log', 'bang', 'cot', 'tieu de', 'test', 'truy van', 'commit', 'script', 'component', 'mat khau', 'video', 'hinh anh', 'du lieu', 'tom tat file', 'tom tat log', 'mo ta'],
    detail: ['chi tiet', 'can ke', 'ky hon', 'ky cang', 'tung buoc', 'sau hon', 'giai thich het', 'giai thich ky', 'phan tich sau', 'ky luong'],
    permission: ['duoc', 'co the', 'khong sao', 'ok', 'duoc roi'],
    lift: ['khong can ngan', 'khong can ngan gon', 'viet dai cung duoc', 'co the viet dai', 'co the chi tiet hon'],
    standing: ['luon luon', 'luon', 'khong bao gio', 'dung bao gio', 'tu gio', 'tu nay', 'tu bay gio', 'moi lan'],
    oneOff: ['tam thoi', 'lan nay', 'bay gio thoi'],
    negation: ['khong dung', 'dung dung', 'khong co', 'bo'],
    emoji: ['emoji', 'bieu tuong cam xuc', 'icon'],
    stop: ['la', 'va', 'cua', 'khong', 'co', 'cho', 'toi', 'ban', 'nay', 'duoc', 'nhu', 'mot', 'gi', 'thi', 'nhe', 'di', 'lam', 'minh', 'cai', 'do', 'sao', 'the', 'nao', 'o', 'dau', 'roi', 'voi', 'tai', 'vi', 'neu'],
    chars: /[ăâđêôơưạảấầẩẫậắằẳẵặẹẻẽếềểễệỉịọỏốồổỗộớờởỡợụủứừửữựỳỵỷỹ]/,
    much: ['nhieu', 'qua nhieu'],
    skip: ['bo qua', 'khoi', 'dung', 'khong can'],
    explain: ['giai thich', 'ly thuyet', 'noi'],
    longform: ['van', 'luan van', 'tieu thuyet', 'sach', 'bai van'],
    text: ['chu', 'van ban'],
    cancel: ['quen', 'huy', 'bo qua', 'khoi'],
    noNeed: ['khong can', 'khoi can', 'khong phai'],
    again: ['lai', 'gio', 'tu gio', 'bay gio', 'duoc roi'],
    briefNoun: ['ngan', 'ngan gon', 'quy tac'],
    answer: ['tra loi'],
    strong: ['it noi nhieu code', 'it noi', 'co hay khong', 'mot cau', 'mot dong', 'khong doc noi'],
  },
  ar: {
    name: 'Arabic',
    brevity: ['باختصار', 'اختصر', 'بايجاز', 'باقتضاب', 'جواب قصير', 'اجابه قصيره', 'اقصر', 'طويل جدا', 'طويله جدا', 'مختصر', 'في سطر واحد', 'بجمله واحده', 'في جمله واحده', 'ادخل في الموضوع', 'الجواب فقط', 'بدون اطاله', 'لا تطول', 'لا تطيل', 'كلام كثير', 'رد قصير', 'ردود قصيره', 'كلام اقل', 'مش رح اقرا', 'مش هقرا', 'ما راح اقرا', 'نعم او لا', 'اختصرها', 'قصرها', 'بدون شرح', 'تجاوز الشرح', 'لا تشرح', 'طويييل', 'بسطر'],
    long: ['طويل', 'طويله', 'مطول', 'مطوله', 'الطويل*', 'طويل*', 'تطول', 'تطويل'],
    too: ['جدا', 'اكثر من اللازم', 'كثيرا', 'زياده'],
    short: ['قصير', 'قصيره', 'مختصر', 'مختصره', 'موجز'],
    reply: ['جواب', 'اجابه', 'الاجابه', 'رد', 'ردود', 'ردك', 'رساله', 'شرح', 'اشرح', 'اكتب', 'اجاباتك'],
    code: ['داله', 'الداله', 'دوال', 'متغير', 'اسم', 'كود', 'الكود', 'ملف', 'كلاس', 'رابط', 'قائمه', 'مصفوفه', 'سجل', 'جدول', 'عمود', 'عنوان', 'اختبار', 'استعلام', 'كوميت', 'سكربت', 'مكون', 'كلمه المرور', 'فيديو', 'صوره', 'بيانات', 'لخص هذا', 'لخص الملف', 'قسم', 'وصف'],
    detail: ['بالتفصيل', 'تفصيل', 'مفصل', 'مفصله', 'بشكل مفصل', 'بعمق', 'خطوه بخطوه', 'اشرح كل شيء', 'بشكل دقيق', 'بدقه'],
    permission: ['يمكنك', 'تقدر', 'ممكن', 'لا باس', 'عادي', 'مسموح', 'تمام'],
    lift: ['لا داعي للاختصار', 'لا تحتاج للاختصار', 'يمكنك الاطاله', 'يمكنك التفصيل', 'لا داعي للايجاز'],
    standing: ['دائما', 'ابدا', 'من الان فصاعدا', 'من الان', 'في كل مره', 'كل مره', 'بعد الان', 'من اليوم', 'ورايح'],
    oneOff: ['حاليا', 'هذه المره', 'مؤقتا', 'الان فقط'],
    negation: ['بدون', 'لا تستخدم', 'لا تضع'],
    emoji: ['ايموجي', 'رموز تعبيريه', 'الرموز التعبيريه', 'emoji'],
    much: ['كثير', 'كتير', 'واجد'],
    skip: ['تجاوز', 'بدون', 'لا تشرح', 'خلاص', 'ما يحتاج'],
    explain: ['الشرح', 'شرح', 'كلام', 'تنظير'],
    longform: ['مقاله', 'رساله ماجستير', 'رساله دكتوراه', 'كتاب', 'روايه', 'موسوعه'],
    text: ['نص', 'كلام'],
    cancel: ['انسى', 'انس', 'الغ', 'ألغ', 'الغيت', 'تجاهل'],
    noNeed: ['ما يحتاج', 'لا داعي', 'مش لازم', 'ما في داعي'],
    again: ['الحين', 'الان', 'ترجع', 'مره ثانيه', 'بعد الان', 'من جديد'],
    briefNoun: ['تختصر', 'الاختصار', 'قصيره', 'مختصر', 'قاعده'],
    stop: ['في', 'من', 'على', 'الى', 'عن', 'هذا', 'هذه', 'ولا', 'بس', 'يا', 'انا', 'انت', 'ليش', 'وين', 'كيف', 'شو', 'ايش', 'والله'],
    answer: ['جواب', 'اجابه', 'الاجابه', 'رد', 'ردود', 'ردك'],
    strong: ['كلام اقل كود اكثر', 'كلام اقل', 'نعم او لا', 'بسطر واحد', 'في سطر واحد', 'بجمله واحده'],
  },
  cs: {
    name: 'Czech',
    brevity: ['strucne', 'kratce', 've zkratce', 'zkratka', 'strucneji', 'kratsi odpoved*', 'kratsi odpovedi', 'kratka odpoved', 'k veci', 'k jadru veci', 'jednou vetou', 'v jedne vete', 'na jeden radek', 'mene textu', 'bez omacky', 'jen odpoved', 'nepis romany', 'nepis roman', 'pis kratce', 'kratsi prosim', 'moc textu', 'min kecu', 'zadne kecy', 'necti', 'nebudu to cist', 'ano nebo ne', 'zkrat to', 'zkrat', 'bez vysvetlovani', 'prestan vysvetlovat', 'preskoc vysvetlovani'],
    long: ['dlouh*', 'rozvlacn*', 'zdlouhav*', 'romany', 'roman', 'delsi', 'delsich'],
    too: ['moc', 'prilis', 'prespris', 'strasne', 'hrozne'],
    short: ['kratk*', 'kratsi*', 'strucn*', 'rychle'],
    reply: ['odpoved*', 'odpovidej', 'zprav*', 'vysvetl*', 'pis', 'napis', 'text*'],
    code: ['funkc*', 'metod*', 'promenn*', 'jmeno', 'nazev', 'nazvy', 'kod', 'kodu', 'soubor*', 'trid*', 'url*', 'odkaz*', 'retez*', 'seznam*', 'pole', 'log', 'logy', 'tabulk*', 'sloup*', 'nadpis*', 'dotaz*', 'commit*', 'skript*', 'komponent*', 'heslo', 'hesl*', 'video', 'obrazek*', 'data', 'shrn tento', 'shrn ten', 'shrnuti', 'sekce', 'popis*', 'test', 'tests'],
    detail: ['podrobne', 'podrobn*', 'detailne', 'detailn*', 'do hloubky', 'dukladne', 'krok za krokem', 'vysvetli vsechno', 'rozeps*'],
    permission: ['muzes', 'klidne', 'je to v pohode', 'ok', 'v pohode'],
    lift: ['nemusis psat strucne', 'uz nemusis byt strucny', 'muzes psat delsi', 'muzes se rozepsat', 'nemusis byt strucny', 'klidne pis delsi'],
    standing: ['vzdy', 'vzdycky', 'nikdy', 'od ted', 'od tedka', 'odted', 'pokazde', 'odedneska'],
    oneOff: ['zatim', 'tentokrat', 'prozatim', 'jen tentokrat'],
    negation: ['bez', 'nepouzivej', 'zadne', 'zadn*'],
    emoji: ['emoji', 'smajl*', 'emotikon*'],
    stop: ['a', 'je', 'to', 'se', 'na', 'v', 'ze', 'ne', 'jak', 'co', 'mi', 'prosim', 'pro', 's', 'ale', 'jsem', 'moc', 'pis', 'uz', 'tvoje', 'ten', 'ta', 'tu', 'ty', 'do', 'od', 'po', 'jen', 'taky', 'tady', 'kde', 'proc', 'dej', 'rekni', 'udelej', 'muzu', 'chci', 'mam', 'jsi'],
    chars: /[řůě]/,
    much: ['moc', 'hodne', 'tolik'],
    skip: ['preskoc', 'bez', 'prestan', 'nemusis', 'dost'],
    explain: ['vysvetlovani', 'vysvetlovat', 'vysvetleni', 'kecy', 'kecu', 'teorie'],
    longform: ['slohovk*', 'diplomk*', 'roman', 'esej', 'kniha', 'bible', 'elaborat'],
    text: ['textu', 'text', 'slov'],
    cancel: ['zapomen', 'zrus', 'ignoruj', 'rusim', 'zrus*'],
    noNeed: ['nemusis', 'uz nemusis', 'neni treba', 'neni potreba'],
    again: ['zase', 'uz', 'ted', 'znovu', 'odted'],
    briefNoun: ['strucny', 'strucne', 'kratce', 'kratky', 'strohy', 'pravidlo'],
    answer: ['odpoved*'],
    strong: ['min kecu vic kodu', 'ano nebo ne', 'jednou vetou', 'na jeden radek', 'k veci'],
  },
  sv: {
    name: 'Swedish',
    brevity: ['kort sagt', 'i korthet', 'kortfattat', 'hall det kort', 'var kort', 'var kortfattad', 'kortare tack', 'kortare svar', 'kort svar', 'rakt pa sak', 'till saken', 'pa en rad', 'i en mening', 'med en mening', 'mindre text', 'bara svaret', 'kort tack', 'koncist', 'skriv kortare', 'mindre snack', 'mindre prat', 'orkar inte lasa', 'laser inte', 'ja eller nej', 'korta ner', 'kortare', 'utan forklaring', 'sluta forklara', 'skippa forklaringen', 'en mening'],
    long: ['lang*', 'langrandig*', 'mangordig*'],
    too: ['for', 'alldeles for', 'valdigt', 'jatte', 'sa'],
    short: ['kort*', 'kortfattad*', 'koncis*'],
    reply: ['svar*', 'meddelande*', 'forklar*', 'skriv*', 'text*'],
    code: ['funktion*', 'metod*', 'variabel*', 'namn*', 'kod', 'koden', 'fil', 'filen', 'filer*', 'kodrad*', 'klass*', 'url*', 'lank*', 'strang*', 'list', 'lists', 'array*', 'logg*', 'tabell*', 'kolumn*', 'titel*', 'rubrik*', 'commit*', 'skript*', 'komponent*', 'losenord*', 'video*', 'bild*', 'data', 'sammanfatta den', 'sammanfatta filen', 'sammanfattning av', 'avsnitt*', 'beskrivning*', 'test', 'tests'],
    detail: ['detaljerat', 'detaljerad*', 'i detalj', 'utforlig*', 'utforligt', 'grundlig*', 'grundligt', 'steg for steg', 'pa djupet', 'forklara allt', 'noggrant', 'noggrann*', 'breda ut'],
    permission: ['far', 'kan', 'gar bra', 'okej', 'ok', 'helt okej', 'ar ok', 'ar okej'],
    lift: ['behover inte vara kort', 'du behover inte vara kortfattad', 'du far skriva langre', 'du kan skriva langre', 'behover inte vara kortfattad'],
    standing: ['alltid', 'aldrig', 'fran och med nu', 'framover', 'varje gang', 'hadanefter'],
    oneOff: ['for tillfallet', 'den har gangen', 'just nu', 'tills vidare', 'for nu'],
    negation: ['inga', 'utan', 'anvand inte', 'ingen', 'inget'],
    emoji: ['emoji*', 'emojis'],
    stop: ['och', 'ar', 'att', 'det', 'som', 'en', 'pa', 'inte', 'jag', 'du', 'med', 'for', 'vad', 'hur', 'kan', 'snalla', 'den', 'dina', 'tack', 'mig', 'i', 'av', 'till', 'om', 'men', 'bara', 'ocksa', 'har', 'var', 'varfor', 'ge', 'sag', 'gor', 'dig', 'nej', 'ja', 'sa'],
    chars: /[å]/,
    much: ['mycket', 'sa mycket', 'for mycket'],
    skip: ['skippa', 'hoppa over', 'utan', 'sluta', 'nog med'],
    explain: ['forklaring*', 'forklara', 'snack', 'prat', 'teori'],
    longform: ['roman', 'uppsats', 'avhandling', 'bok', 'bibel', 'essa'],
    text: ['text', 'ord'],
    cancel: ['glom', 'strunta i', 'ignorera', 'tar bort regeln', 'ta bort regeln'],
    noNeed: ['behover inte', 'inte langre', 'inte nodvandigt'],
    again: ['igen', 'nu', 'fran och med nu', 'tillbaka'],
    briefNoun: ['kort', 'korta', 'kortfattad', 'regeln'],
    answer: ['svar*'],
    strong: ['mindre snack mer kod', 'mindre text mer kod', 'ja eller nej', 'en mening', 'pa en rad', 'rakt pa sak'],
  },
};
